name: 'go-buildinfo'
description: 'Helps populate buildinfo for Go.'
author: 'Naitik Shah'
inputs:
  release_version:
    description: 'Specify release version to use. Automatically determined if unset.'
runs:
  using: 'node12'
  main: 'dist/index.js'
