name: "build-test"
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'
    - name: install
      run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - uses: ./
    - name: Env
      run: echo $BI_LDFLAGS
    - name: Build
      run: go build -ldflags="$BI_LDFLAGS" -trimpath
    - name: Execute
      run: ./go-buildinfo
