name: "build-test"
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.1
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.15'
    - uses: actions/checkout@v2.1.1
    - uses: ./
    - name: Env
      run: echo $BI_LDFLAGS
    - name: Build
      run: go build -ldflags="$BI_LDFLAGS" -trimpath
    - name: Execute
      run: ./go-buildinfo
